services:
  postgres:
    image: postgres:16-alpine3.20
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: birthday_messager

  api-service:
    build: .
    # image: nwaoghor/auto-birthday-messager:1.0.0
    ports:
      - ${PORT}:${PORT}
      - 9229:9229 #debug
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.pnpm-store
      - /usr/src/app/node_modules
    command: pnpm start:docker
    depends_on: 
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}