services:
  api-service:
    # build: .
    image: nwaoghor/auto-birthday-messager:1.0.0
    ports:
      - 3001:3001
      - 9229:9229 #debug
    command: pnpm start:docker
    environment:
      PORT: 3001