 export const {
    PORT,
    DEBUG_PORT,
    POSTGRES_URL,
    DATABASE_URL,
    CRYPTO_SECRET,
    JWT_SECRET,
    REFRESH_TOKEN_SECRET,
    JWT_EXPIRES_IN,
    REFRESH_TOKEN_EXPIRES_IN,
 } = process.env